openapi: 3.0.4
info:
  title: Text to Color
  description: Text to Color is a simple tool for converting color from natural language. It returns the color code based on the text provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/texttocolor:
    get:
      summary: Generate Color from Natual Language
      description: Text to Color is a simple tool for converting color from natural language. It returns the color code based on the text provided.
      operationId: texttocolor
      parameters:
      - name: color
        in: query
        schema:
          type: string
        required: true
        description: The text to convert the color from
        example: turquoise
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  color: turquoise
                  hex: '#66c8b8'
                  rgb: 102, 200, 184
                  hsl: 170, 47, 59
                  cmyk: 49, 0, 8, 22
                  ansi16: 96
                  channels:
                    rgbChannels: 3
                    cmykChannels: 4
                    ansiChannels: 1
                    hexChannels: 1
                    hslChannels: 3
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
